### PR TITLE
Update German MARC 21 data sources

### PR DESCRIPTION
**Pull request by hemmefelix**
url corrections, removed SWB because the url was invalid and I couldn't find a new one

### CODE REVIEW

**Comment by pkiraly** [comment]
@hemmefelix Many thanks! Do you have - by chance - any contact info we can ask about the data dump?

**Comment by pkiraly** [comment]
I found the impression of the site: https://www.bsz-bw.de/impressum.html. I'll write them

**Comment by hemmefelix** [comment]
Hi @pkiraly , I would assume that the data dump is no longer provided after SWB and GBV merged their catalogues into K10plus union catalog. K10plus does not provide data dumps, but rather SRU and Z39.50. OAI-PMH is only experimental and not public accessible.

**Comment by pkiraly** [comment]
@hemmefelix Therre is a high chance for it.

**Comment by pkiraly** [comment]
@hemmefelix Thanks a lot for the contribution! I merged this pull request into the codebase, so you became a contributor.

**Pull request merged**
